config/routes.rb
BadJokes::Application.routes.draw do

  root 'jokes#index'

  resources :jokes

end

app/models/joke.rb
class Joke < ActiveRecord::Base
  validates :question, :presence => true
  validates :answer, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @joke = Joke.order("RANDOM()").first
  end

  def new
    @joke = Joke.new
  end

  def create
    @joke = Joke.create(joke_params)
    if @joke.invalid?
      flash[:error] = '<strong> You must enter a question and answer </strong>'
    end

    redirect_to root_path
  end

  private

  def joke_params
    params.require(:joke).permit(:question, :answer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/index.html.erb
<body>
  <h1> Welcome to my Silly Joke Page </h1>
  <br /><br />
  <h2><%= @joke.question %></h2>
  <h3><%= @joke.answer %></h3>
  <br /><br /><br />
  <%= link_to 'Next Joke', root_path, :class => 'next-link' %>
  <%= link_to 'Add a Joke', new_joke_path, :class => 'add-link' %>
</body>

app/views/jokes/new.html.erb
<h1>Enter your bad joke here</h1>
<%= simple_form_for @joke do |f| %>
  <%= f.input :question %>
  <%= f.input :answer %>
  <br />
  <%= f.submit 'Create', :class => 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BadJokes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>